"use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React, { useState } from "react";
import { Header } from "@/components/header/Header";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const PageContext = React.createContext({
  mode: false,
  setMode: (mode: boolean) => {},
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [mode, setMode] = useState(false);

  return (
    <html lang="en">
      <body className={`${inter.className} ${mode ? "body_dark-mode" : ""}`}>
        <PageContext.Provider value={{ mode, setMode }}>
          <header>
            <Header />
          </header>
          <main>{children}</main>
        </PageContext.Provider>
      </body>
    </html>
  );
}
